# -*- coding: utf-8 -*-
"""Pima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/0B2pUTZuo8T7lb0h6T3FXUzJVdXlHb1FneEpLUC1xb2oxQ3hv
"""

import sklearn.metrics 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

dataset= np.loadtxt('/home/samridhi/Desktop/LP1/DA/pima-indians-diabetes.csv',delimiter=',')

dataset

x_train = dataset[0:667,0:8]
y_train = dataset[0:667,8:9]
x_test = dataset[667:777,0:8]
y_test = dataset[667:777,8:9]

model = GaussianNB()

model.fit(x_train,y_train.ravel())

predicted = model.predict(x_test)

print(predicted)

score = sklearn.metrics.accuracy_score(y_test,predicted)

print(score)
